import { describe, expect, it } from 'vitest';

import { authoringStylesCss } from './authoring-styles.js';

// The same reasoning `caseload-styles.test.ts` and `record-styles.test.ts`
// set out: a stylesheet held as a string can be read as text, and the
// coupling worth checking is between a class a component emits and a rule
// that styles it. The classes are string literals in JSX, so a rename on
// either side compiles clean and simply stops working.

/** Every class this stylesheet exists to style, and the component that writes it. */
const EMITTED_CLASSES = [
  // BlogComposer.tsx / WorkshopComposer.tsx / AuthoredContentList.tsx
  'ndn-authoring-sheet',
  'ndn-authoring-intro',
  'ndn-authoring-hint',
  'ndn-authoring-alert',
  'ndn-authoring-keywords',
  'ndn-authoring-publish',
  // MediaUploadField.tsx
  'ndn-authoring-media',
  'ndn-authoring-file',
  'ndn-authoring-media-preview',
  // AuthoredContentList.tsx
  'ndn-authored-scroll',
  'ndn-authored-table',
  'ndn-authored-title',
  'ndn-authored-status',
  'ndn-authored-status--published',
  'ndn-authored-status--draft',
];

describe('authoringStylesCss', () => {
  it('styles every class the authoring components emit', () => {
    for (const className of EMITTED_CLASSES) {
      expect(authoringStylesCss, `no rule for .${className}`).toContain(`.${className}`);
    }
  });

  // The owner: *"the browse and save etc buttons doesnt have a nice
  // bootstrap look."* Save became `packages/ui`'s own `Button`, which needs
  // nothing here. Browse could not: it is generated by the browser inside
  // the file input's shadow tree, and `::file-selector-button` is the only
  // selector that reaches it. Without these rules it renders as the
  // platform's grey "Choose File" chip next to a row of brand pills.
  it('reaches the Browse button inside the file input, for both file fields', () => {
    expect(authoringStylesCss).toContain('.ndn-authoring-file::file-selector-button');
    expect(authoringStylesCss).toContain(".ndn-rte-panel input[type='file']::file-selector-button");
  });

  it('gives the posts table a status badge per state', () => {
    // Published or not — the two states a content item has. A badge that
    // silently lost one would render a draft in the same tint as a live
    // post, which is the one thing this column exists to tell apart.
    for (const state of ['published', 'draft']) {
      expect(authoringStylesCss, `no badge for "${state}"`).toContain(
        `.ndn-authored-status--${state}`,
      );
    }
  });

  it('lets the posts table scroll inside its own container rather than the page', () => {
    expect(authoringStylesCss).toContain('.ndn-authored-scroll');
    expect(authoringStylesCss).toContain('overflow-x: auto');
  });

  it('restates a focus outline for its own hand-written controls', () => {
    // Not `packages/ui` primitives, so they inherit none of
    // `.ndn-interactive`'s focus styling — the same restatement
    // `caseload-styles.ts` makes for the same reason.
    expect(authoringStylesCss).toContain('.ndn-authoring-file:focus-visible');
    expect(authoringStylesCss).toContain('.ndn-authored-title:focus-visible');
  });

  it('beats the primitive stylesheet on specificity rather than on order', () => {
    // Astro decides which of several `<style set:html>` elements lands
    // first, so a rule that only wins on source order stops winning when
    // something moves.
    expect(authoringStylesCss).toContain('.ndn-authoring-sheet > h2.ndn-heading');
    expect(authoringStylesCss).toContain('.ndn-authoring-sheet .ndn-input-label');
  });

  it('carries no raw colour — every value comes from tokens/color.ts', () => {
    expect(authoringStylesCss).not.toMatch(/#[0-9a-fA-F]{3,8}\b/);
    expect(authoringStylesCss).not.toMatch(/\brgba?\(/);
  });

  it('carries no backtick, which would end the template literal it lives in', () => {
    expect(authoringStylesCss).not.toContain('`');
  });
});
