// D-29 (2026-08-29): a patient's password is generated by this platform,
// not chosen by them — `patient-admin.ts`'s whole point is that nobody
// self-serves a password here. `AdminSetUserPassword` needs a value that
// already satisfies the patient pool's policy (auth-stack.ts: length 8,
// lower, upper, digit, symbol — the same shape the clinician pool uses),
// so this builds one that always does, rather than generating blind and
// retrying against Cognito's own rejection.
//
// SDK-free and pure — `crypto.randomInt` is Node's own CSPRNG, not
// `Math.random()`, the same distinction sms-rate-limiter.ts's own token
// generation already draws.
import { randomInt } from 'node:crypto';

/**
 * Ambiguous characters excluded on purpose: this password is read aloud or
 * typed over WhatsApp by a human relaying it to another human, and `0`/`O`,
 * `1`/`l`/`I` are exactly the pairs a typo turns into a locked-out patient
 * and a second WhatsApp round trip. Narrowing the alphabet costs entropy;
 * at 16 characters across four character classes there is plenty to spare
 * for what this protects.
 */
const LOWERCASE = 'abcdefghjkmnpqrstuvwxyz';
const UPPERCASE = 'ABCDEFGHJKMNPQRSTUVWXYZ';
const DIGITS = '23456789';
const SYMBOLS = '!@#$%&*+=?';

const ALL_CHARACTERS = LOWERCASE + UPPERCASE + DIGITS + SYMBOLS;

/**
 * 16, not the policy's own minimum of 8 — this password is never memorised
 * or typed by the person it belongs to on an ongoing basis (it goes
 * straight into a saved browser/app credential, per the WhatsApp-mediated
 * model's own design), so there is no usability cost to spending the extra
 * length on strength.
 */
export const GENERATED_PASSWORD_LENGTH = 16;

function randomCharacterFrom(alphabet: string): string {
  return alphabet[randomInt(alphabet.length)] as string;
}

/** Fisher-Yates, using the same CSPRNG as every other draw in this file — a sorted-by-Math.random shuffle is not uniform and would undo the point of a secure source. */
function shuffle(characters: string[]): string[] {
  const shuffled = [...characters];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = randomInt(i + 1);
    [shuffled[i], shuffled[j]] = [shuffled[j] as string, shuffled[i] as string];
  }
  return shuffled;
}

/**
 * Guarantees at least one character from each of the four classes
 * Cognito's password policy requires, then fills the remaining length from
 * the full alphabet and shuffles — never four fixed positions, which would
 * make the first four characters of every generated password predictable.
 */
export function generatePassword(): string {
  const required = [
    randomCharacterFrom(LOWERCASE),
    randomCharacterFrom(UPPERCASE),
    randomCharacterFrom(DIGITS),
    randomCharacterFrom(SYMBOLS),
  ];
  const remaining = Array.from({ length: GENERATED_PASSWORD_LENGTH - required.length }, () =>
    randomCharacterFrom(ALL_CHARACTERS),
  );
  return shuffle([...required, ...remaining]).join('');
}
