// TASK 1.5.2 (ADR-0010): "POST /workshops/:id/checkout" — kept deliberately
// SDK-free and HTTP-free, same shape as contact-form.ts's
// createContactFormHandler, not workshop-authoring.ts's HTTP-shaped
// handler: capacity reservation -> Stripe Checkout Session creation ->
// registration row is unit-testable with zero AWS/Stripe.
// stripe-checkout-handler.ts is the HTTP boundary: it parses the untrusted
// request body, generates the registration id, hashes the caller's IP into
// `principal` before this file ever sees it, resolves the real Stripe
// secret key, and maps WorkshopCheckoutResult to a status code.
import type { Clock } from './clock.js';
import { systemClock } from './clock.js';
import type { RegistrationRepository } from './registration-repository.js';
import type { WorkshopRepository } from './workshop-repository.js';

export interface CheckoutSession {
  readonly id: string;
  readonly url: string;
}

export interface CreateCheckoutSessionInput {
  readonly workshopId: string;
  readonly workshopTitle: string;
  readonly priceMinorUnits: number;
  /**
   * `REGISTRATION#<id>` — set as the Checkout Session's own
   * `client_reference_id` (TASK 1.5.2's own Interfaces note). `workshopId`
   * travels separately as the session's `metadata.workshopId`
   * (stripe-checkout-handler.ts) since a single client_reference_id string
   * can't be split back into this table's pk *and* sk without inventing a
   * delimiter convention that duplicates what metadata already exists for.
   */
  readonly clientReferenceId: string;
}

/** The one Stripe API call this file ever needs, injected so no test calls the real Stripe API — stripe-checkout-handler.ts is the only place that calls the real `stripe` SDK. */
export type CreateCheckoutSession = (
  input: CreateCheckoutSessionInput,
) => Promise<CheckoutSession>;

export type WorkshopCheckoutResult =
  | { kind: 'created'; checkoutUrl: string }
  /** The workshop doesn't exist, isn't published, or has already happened — never distinguished in the response (no leaking draft/cancelled-workshop existence). */
  | { kind: 'unavailable' }
  | { kind: 'full' };

export interface WorkshopCheckoutRequest {
  readonly workshopId: string;
  /** Generated by the HTTP boundary — injectable so tests can assert on a known id, same convention testimonial-submission.ts's SubmitTestimonialInput.id documents. */
  readonly registrationId: string;
  readonly attendeeEmail: string;
  /**
   * A hashed identity for the audit trail — stripe-checkout-handler.ts
   * hashes the caller's source IP (SHA-256), same convention
   * contact-form-handler.ts/testimonial-submission-handler.ts use; this
   * file never receives, stores, or logs the raw address.
   */
  readonly principal: string;
}

export interface WorkshopCheckoutDeps {
  readonly workshops: WorkshopRepository;
  readonly registrations: RegistrationRepository;
  readonly createCheckoutSession: CreateCheckoutSession;
  readonly clock?: Clock;
}

export function createWorkshopCheckoutHandler(
  deps: WorkshopCheckoutDeps,
): (req: WorkshopCheckoutRequest) => Promise<WorkshopCheckoutResult> {
  const clock = deps.clock ?? systemClock;

  return async (req) => {
    const workshop = await deps.workshops.findById(req.workshopId);
    const nowIso = clock.now().toISOString();
    // Same "published, not-yet-happened" boundary workshop-repository.ts's
    // findPublishedUpcoming enforces for the public listing — a draft,
    // cancelled, or already-happened workshop can never be checked out
    // against, even by a client that already knows its id.
    if (!workshop || workshop.status !== 'published' || workshop.dateTimeUtc < nowIso) {
      return { kind: 'unavailable' };
    }

    // Capacity reserved *before* calling Stripe — a workshop already at
    // capacity never triggers a Checkout Session creation at all.
    const reserved = await deps.registrations.reserveCapacity(req.workshopId, workshop.capacity);
    if (!reserved) {
      return { kind: 'full' };
    }

    const workshopTitle = Object.values(workshop.details)[0]?.title ?? workshop.id;

    let session: CheckoutSession;
    try {
      session = await deps.createCheckoutSession({
        workshopId: req.workshopId,
        workshopTitle,
        priceMinorUnits: workshop.priceMinorUnits,
        clientReferenceId: `REGISTRATION#${req.registrationId}`,
      });
    } catch (error) {
      // The Stripe call that was meant to follow this reservation failed —
      // release it rather than leaking a slot no session will ever expire.
      await deps.registrations.releaseCapacity(req.workshopId);
      throw error;
    }

    await deps.registrations.create(req.principal, {
      id: req.registrationId,
      workshopId: req.workshopId,
      attendeeEmail: req.attendeeEmail,
      stripeCheckoutSessionId: session.id,
    });

    return { kind: 'created', checkoutUrl: session.url };
  };
}
